### ISSUE TITLE
Add WDIO sync -> async codemod

### ISSUE THREAD

**Issue by vgrigoruk** [webdriverio/codemod#1]
It would be nice to have a `codemod` that can convert `wdio` sync code to async.

**Comment by alk-mandrianarijaona** [comment]
Hello, has anyone started to work on the codemod? This is something I am going to need to I am offering my help

**Comment by alk-mandrianarijaona** [comment]
@christian-bromann I have started a draft PR to start collaborating on this

**Comment by mo** [comment]
I tried this codemode and it got me a little bit on the way but many things needs manual fixups. In particular:
* it added double/nested awaits, for example: ```expect(await (await $('body')).getText()).toContain('Could not find any page matching the specified address.')```
* it added "async" on each test like for example ```it('login page loads', async () => {``` but I use page objects so most of my .click() and .setValue() etc is inside page object functions and those where not made async. Whenever it adds an await in a function, I think it would be good if that function was also made async.

**Comment by alk-mandrianarijaona** [comment]
@mo would you mind sharing some of your initial code sample so I can do more testing on my side?

**Comment by WillBrock** [comment]
I expanded off of what @alk-mandrianarijaona started with the codemod if anyone wants to check it out.

https://github.com/webdriverio/codemod/pull/53

**Comment by alk-mandrianarijaona** [comment]
@WillBrock that looks great, I am gonna test it with some of my files and let you know

**Comment by bitfrost** [comment]
Any updates on the status of this effort?
