### ISSUE TITLE
browser.saveScreenshot(filepath); - Why its not accepting filePath as outside of project Directory?

### ISSUE THREAD

**Issue by Sweetie7** [webdriverio/codemod#128]

**Comment by christian-bromann** [comment]
Can you please provide a description of your problem?

**Comment by Sweetie7** [comment]
browser.saveScreenshot(filepath);
Project directory - C:/Project
filepath - C:/Logs/Screenshots/
name - project_QA_0416202408011234
browser.saveScreenshots(filepath+name.png);

Getting error as cannot find path to savescreenshot as its concatinating the path - 'C:/ProjectC:/Logs/Screenshots/'

**Comment by christian-bromann** [comment]
> 'C:/ProjectC:/Logs/Screenshots/'

This is not a valid path, I recommend use Node.js utilities like `path.resolve(...)`. This doesn't seem like a WebdriverIO issue, therefor I will close it. I recommend to join the discord channel for questions like this.

**Comment by Sweetie7** [comment]
That is what why its merging project directory path wit filepath?
