### ISSUE TITLE
Chained protractor selectors aren't transformed correctly

### ISSUE THREAD

**Issue by alebx** [webdriverio/codemod#29]
When transforming this chained selector:
```
await table.element(by.className('datatable-header')).all(by.className('datatable-header-cell-label'))).click();
```

It turns into this:
```
await table.$(".datatable-header").$$(".datatable-header-cell-label").click();
```

Which isn't a valid async selector.

**Comment by christian-bromann** [comment]
@alebx thanks for reporting!

Can you explain what happens here:
```js
await table.element(by.className('datatable-header')).all(by.className('datatable-header-cell-label'))).click();
```

is it clicking on all elements it finds?

**Comment by alebx** [comment]
@christian-bromann thanks for the quick reply!
Yes, that's exactly what's happening. I know I could rewrite the selector, but that would mean a major rewrite of our code base.

**Comment by christian-bromann** [comment]
So WebdriverIO with the latest version allows you to click on specific elements, e.g.:
```js
await table.$(".datatable-header").$$(".datatable-header-cell-label")[0].click();
```
but it won't click on all elements. You would need to iterate over them, e.g.:

```js
await for (const elem of table.$(".datatable-header").$$(".datatable-header-cell-label")) {
    await elem.click()
}
```

**Comment by christian-bromann** [comment]
I think this issue is resolved. Closing.
