### ISSUE TITLE
env: node\r: No such file or directory 

### ISSUE THREAD

**Issue by mekalag** [webdriverio/codemod#32]
Hi everyone, I am trying to transform a file called baseSteps.js to webdriverIO file using command 

npx jscodeshift ../node_modules/\@wdio/codemod/protractor/ test/steps/baseSteps.js

Before this i have installed : 
*npm install --save-dev @wdio/cli*
*npx wdio config  (ran the configuration wizard)  I have configured cucumber framework.*

After which I ran 
*npx jscodeshift ../node_modules/\@wdio/codemod/protractor/ test/steps/baseSteps.js*

In package.json I have all the dependencies 
<img width="551" alt="Screenshot 2021-07-03 at 18 52 06" src="https://user-images.githubusercontent.com/11612209/124361512-d0d31480-dc2f-11eb-9c82-28706175a73f.png">

So when I run npx jscodeshift ../node_modules/\@wdio/codemod/protractor/ test/steps/baseSteps.js
it throws : 
env: node\r: No such file or directory

Not sure what I am missing. though baseSteps.js file exists in test/steps folder. Can someone suggest? 

Note: I am using mac OS. I was going through help in some other articles and I think this issue is caused by line endings with CRLF, where as its must be LF. For ex:  https://github.com/mrmlnc/svg2sprite-cli/issues/4
and many more when we search for `env: node\r: No such file or directory` hopefully this will give an idea

**Comment by christian-bromann** [comment]
You were missing a parameter, see our [`Usage`](https://github.com/webdriverio/codemod#usage) section, I believe it is suppose to be this way:

```sh
npx jscodeshift -t ./node_modules/@wdio/codemod/protractor ./test/steps/baseSteps.js
```

Please let me know if you have further questions.

**Comment by mekalag** [comment]
Unfortunately, using -t parameter dint help.  Its still throws `env: node\r: No such file or directory`.

**Comment by erickzhao** [comment]
For reference, I think this is an upstream issue with `jscodeshift`: https://github.com/facebook/jscodeshift/issues/424

**Comment by kliph-gladly** [comment]
It would be helpful to update the docs to indicate that the workaround described here https://github.com/facebook/jscodeshift/issues/424#issuecomment-888243971 works.

**Comment by christian-bromann** [comment]
@kliph-gladly mind raising a PR?

**Comment by kliph-gladly** [comment]
I've encountered larger issues with the `@wdio/codemod/async` adding `await` keyword to function calls for functions that do not return promises and failing to add `async` to anonymous inline functions.  I anticipate that I won't be using this in the future.

**Comment by christian-bromann** [comment]
You will only need the codemod package as utility to rewrite your tests.

**Comment by kliph-gladly** [comment]
Thanks.  Yes I'm aware.  The larger issue that I mentioned is that the utility produces code with syntax errors.

**Comment by christian-bromann** [comment]
Can you provide a code example that causes a syntax error when rewriting the code with this codemod?

**Comment by kliph-gladly** [comment]
Sure:

```
const foo = function() {
  mySyncFunctionDoesNotReturnAPromiseOrEvenExist();
};
```

produces

```
const foo = function() {
  await mySyncFunctionDoesNotReturnAPromiseOrEvenExist();
};
```

This is syntactically incorrect for two reasons, the outer function context is not `async` so it doesn't make sense to use `await` within it.  And the function called in the inner scope does not return a promise, so it doesn't make sense to use `await`.

**Comment by christian-bromann** [comment]
Yep, this is a bug, mind raising a new issue for it?

**Comment by kliph-gladly** [comment]
Will do.  Thank you.
