### ISSUE TITLE
protractor.ExpectedConditions" is unknown to this codemod

### ISSUE THREAD

**Issue by irisda** [webdriverio/codemod#39]
protractor.ExpectedConditions" is unknown to this codemod

**Comment by christian-bromann** [comment]
The codemod transforms these properly, see [here](https://github.com/webdriverio/codemod/blob/3993da6cebc7b58814d8413b2f6e9d29aa6af087/protractor/index.js#L706-L709). Do you have a code example that doesn't work for you?

**Comment by irisda** [comment]
yes
  global.EC = protractor.ExpectedConditions;
this is the code that i have inside config.js file
