### ISSUE TITLE
$ or $$ are not recognised in V7 working fine in V5

### ISSUE THREAD

**Issue by diwakar-jha3110** [webdriverio/codemod#42]
Cannot find name '$'. Do you need to install type definitions for jQuery

Also issue with the types as import element = WebdriverIO.Element;
WebdriverIO is getting picked from @wdio/sync not from @wdio/mocha-framework

tsConfig.json is as below
{
"compilerOptions": {
    "baseUrl": ".",
    "lib": ["es2017", "dom"],
    "module": "commonjs",
    "target": "es6",
    "strict": false,
    "strictNullChecks": false,
    "resolveJsonModule": true,
    "typeRoots": [
"./declarations", "./node_modules/@types", "./node_modules/@wdio/@types", "./node_modules/webdriverio/async", "./node_modules/@wdio/mocha-framework"],
    "exclude": ["node_modules"]
}

**Comment by christian-bromann** [comment]
@diwakar-jha3110 thanks for raising an issue. Please see https://webdriver.io/docs/typescript#framework-setup, you need to set the `types` property in your tsconfig file, e.g.:

```json
{
    "compilerOptions": {
        "types": ["node", "webdriverio/sync", "@wdio/mocha-framework"]
    }
}
```
