### ISSUE TITLE
Plans to add support for other locators?

### ISSUE THREAD

**Issue by vasudha0309** [webdriverio/codemod#59]
Any plans to add direct method to findElement by binding or by repeater?

**Comment by christian-bromann** [comment]
@vasudha0309 these are very Angular specific locators and require probably some enhancement to WebdriverIOs locator strategies. WebdriverIO already supports react based locators and it would be great if we can also have better locators for Angular. Any contributions in this direction is welcome.

That said, we can't just create these locators without adding additional functionality into WebdriverIO.

**Comment by christian-bromann** [comment]
Closing as it seems no one was interested adding this feature in WebdriverIO, therefore there is no need to have a codemod for it.
