### ISSUE TITLE
Update version this package 

### ISSUE THREAD

**Issue by seregka23** [webdriverio/codemod#96]
Hi team,

Thanks for your help with the previous question.
  I would like to ask if you could publish new version of your package so we can update it in our repository?

**Comment by christian-bromann** [comment]
Just triggered another release

**Comment by seregka23** [comment]
Hi Team,

@christian-bromann. Thank you for help. But we see that [the action](https://github.com/webdriverio/codemod/actions/runs/4387261205) failed. Could you please restart it?
